export const BOARDDIMENSIONS = [8,8];
export const TILESIZE = 60;
export const TILEBORDERSIZE = 1;
export const LIGHT_TILE = "#f98f39";
export const DARK_TILE = "#603d0b";
export const INIT_SETUP = [
  {name: "wR1", pngPos: "130px -3px", dead: false, clicked: false, xC: 0, yC: 7},
  {name: "wR2", pngPos: "130px -3px", dead: false, clicked: false, xC: 7, yC: 7},
  {name: "wN1", pngPos: "197px -3px", dead: false, clicked: false, xC: 1, yC: 7},
  {name: "wN2", pngPos: "197px -3px", dead: false, clicked: false, xC: 6, yC: 7},
  {name: "wB1", pngPos: "-136px -3px", dead: false, clicked: false, xC: 2, yC: 7},
  {name: "wB2", pngPos: "-136px -3px", dead: false, clicked: false, xC: 5, yC: 7},
  {name: "wK", pngPos: "-4px -3px", dead: false, clicked: false, xC: 4, yC: 7},
  {name: "wQ", pngPos: "-70px -3px", dead: false, clicked: false, xC: 3, yC: 7},
  {name: "wP1", pngPos: "65px -3px", dead: false, clicked: false, xC: 0, yC: 6},
  {name: "wP2", pngPos: "65px -3px", dead: false, clicked: false, xC: 1, yC: 6},
  {name: "wP3", pngPos: "65px -3px", dead: false, clicked: false, xC: 2, yC: 6},
  {name: "wP4", pngPos: "65px -3px", dead: false, clicked: false, xC: 3, yC: 6},
  {name: "wP5", pngPos: "65px -3px", dead: false, clicked: false, xC: 4, yC: 6},
  {name: "wP6", pngPos: "65px -3px", dead: false, clicked: false, xC: 5, yC: 6},
  {name: "wP7", pngPos: "65px -3px", dead: false, clicked: false, xC: 6, yC: 6},
  {name: "wP8", pngPos: "65px -3px", dead: false, clicked: false, xC: 7, yC: 6},
  {name: "bR1", pngPos: "130px 63px", dead: false, clicked: false, xC: 0, yC: 0},
  {name: "bR2", pngPos: "130px 63px", dead: false, clicked: false, xC: 7, yC: 0},
  {name: "bN1", pngPos: "197px 63px", dead: false, clicked: false, xC: 1, yC: 0},
  {name: "bN2", pngPos: "197px 63px", dead: false, clicked: false, xC: 6, yC: 0},
  {name: "bB1", pngPos: "-136px 63px", dead: false, clicked: false, xC: 2, yC: 0},
  {name: "bB2", pngPos: "-136px 63px", dead: false, clicked: false, xC: 5, yC: 0},
  {name: "bK", pngPos: "-4px 63px", dead: false, clicked: false, xC: 4, yC: 0},
  {name: "bQ", pngPos: "-70px 63px", dead: false, clicked: false, xC: 3, yC: 0},
  {name: "bP1", pngPos: "65px 63px", dead: false, clicked: false, xC: 0, yC: 1},
  {name: "bP2", pngPos: "65px 63px", dead: false, clicked: false, xC: 1, yC: 1},
  {name: "bP3", pngPos: "65px 63px", dead: false, clicked: false, xC: 2, yC: 1},
  {name: "bP4", pngPos: "65px 63px", dead: false, clicked: false, xC: 3, yC: 1},
  {name: "bP5", pngPos: "65px 63px", dead: false, clicked: false, xC: 4, yC: 1},
  {name: "bP6", pngPos: "65px 63px", dead: false, clicked: false, xC: 5, yC: 1},
  {name: "bP7", pngPos: "65px 63px", dead: false, clicked: false, xC: 6, yC: 1},
  {name: "bP8", pngPos: "65px 63px", dead: false, clicked: false, xC: 7, yC: 1},
];
//eventually switch to this format

export const PIECE_OBJECTS = {
  "wR1": {pngPos: "130px -3px", dead: false, clicked: false, xC: 0, yC: 7},
  "wR2": {pngPos: "130px -3px", dead: false, clicked: false, xC: 7, yC: 7},
  "wN1": {pngPos: "197px -3px", dead: false, clicked: false, xC: 1, yC: 7},
  "wN2": {pngPos: "197px -3px", dead: false, clicked: false, xC: 6, yC: 7},
  "wB1": {pngPos: "-136px -3px", dead: false, clicked: false, xC: 2, yC: 7},
  "wB2": {pngPos: "-136px -3px", dead: false, clicked: false, xC: 5, yC: 7},
  "wK": {pngPos: "-4px -3px", dead: false, clicked: false, xC: 4, yC: 7},
  "wQ": {pngPos: "-70px -3px", dead: false, clicked: false, xC: 3, yC: 7},
  "wP1": {pngPos: "65px -3px", dead: false, clicked: false, xC: 0, yC: 6},
  "wP2": {pngPos: "65px -3px", dead: false, clicked: false, xC: 1, yC: 6},
  "wP3": {pngPos: "65px -3px", dead: false, clicked: false, xC: 2, yC: 6},
  "wP4": {pngPos: "65px -3px", dead: false, clicked: false, xC: 3, yC: 6},
  "wP5": {pngPos: "65px -3px", dead: false, clicked: false, xC: 4, yC: 6},
  "wP6": {pngPos: "65px -3px", dead: false, clicked: false, xC: 5, yC: 6},
  "wP7": {pngPos: "65px -3px", dead: false, clicked: false, xC: 6, yC: 6},
  "wP8": {pngPos: "65px -3px", dead: false, clicked: false, xC: 7, yC: 6},
  "bR1": {pngPos: "130px 63px", dead: false, clicked: false, xC: 0, yC: 0},
  "bR2": {pngPos: "130px 63px", dead: false, clicked: false, xC: 7, yC: 0},
  "bN1": {pngPos: "197px 63px", dead: false, clicked: false, xC: 1, yC: 0},
  "bN2": {pngPos: "197px 63px", dead: false, clicked: false, xC: 6, yC: 0},
  "bB1": {pngPos: "-136px 63px", dead: false, clicked: false, xC: 2, yC: 0},
  "bB2": {pngPos: "-136px 63px", dead: false, clicked: false, xC: 5, yC: 0},
  "bK": {pngPos: "-4px 63px", dead: false, clicked: false, xC: 4, yC: 0},
  "bQ": {pngPos: "-70px 63px", dead: false, clicked: false, xC: 3, yC: 0},
  "bP1": {pngPos: "65px 63px", dead: false, clicked: false, xC: 0, yC: 1},
  "bP2": {pngPos: "65px 63px", dead: false, clicked: false, xC: 1, yC: 1},
  "bP3": {pngPos: "65px 63px", dead: false, clicked: false, xC: 2, yC: 1},
  "bP4": {pngPos: "65px 63px", dead: false, clicked: false, xC: 3, yC: 1},
  "bP5": {pngPos: "65px 63px", dead: false, clicked: false, xC: 4, yC: 1},
  "bP6": {pngPos: "65px 63px", dead: false, clicked: false, xC: 5, yC: 1},
  "bP7": {pngPos: "65px 63px", dead: false, clicked: false, xC: 6, yC: 1},
  "bP8": {pngPos: "65px 63px", dead: false, clicked: false, xC: 7, yC: 1},
};