export const BOARDDIMENSIONS = [8,8];
export const TILESIZE = 60;
export const TILEBORDERSIZE = 1;
export const LIGHT_TILE = "#f98f39";
export const DARK_TILE = "#603d0b";
export const PIECE_OBJECTS = {
  "wR1": {view: {}, pngPos: "130px -3px", dragging: false, dead: false, clicked: false, xC: 3, yC: 7},
  // "wR2": {view: {}, pngPos: "130px -3px", dragging: false, dead: false, clicked: false, xC: 7, yC: 7},
  // "wN1": {view: {}, pngPos: "197px -3px", dragging: false, dead: false, clicked: false, xC: 1, yC: 7},
  // "wN2": {view: {}, pngPos: "197px -3px", dragging: false, dead: false, clicked: false, xC: 6, yC: 7},
  // "wB1": {view: {}, pngPos: "-136px -3px", dragging: false, dead: false, clicked: false, xC: 2, yC: 7},
  // "wB2": {view: {}, pngPos: "-136px -3px", dragging: false, dead: false, clicked: false, xC: 5, yC: 7},
  // "wK": {view: {}, pngPos: "-4px -3px", dragging: false, dead: false, clicked: false, xC: 4, yC: 7},
  // "wQ": {view: {}, pngPos: "-70px -3px", dragging: false, dead: false, clicked: false, xC: 3, yC: 7},
  // "wP1": {view: {}, pngPos: "65px -3px", dragging: false, dead: false, clicked: false, xC: 0, yC: 6},
  // "wP2": {view: {}, pngPos: "65px -3px", dragging: false, dead: false, clicked: false, xC: 1, yC: 6},
  // "wP3": {view: {}, pngPos: "65px -3px", dragging: false, dead: false, clicked: false, xC: 2, yC: 6},
  // "wP4": {view: {}, pngPos: "65px -3px", dragging: false, dead: false, clicked: false, xC: 3, yC: 6},
  // "wP5": {view: {}, pngPos: "65px -3px", dragging: false, dead: false, clicked: false, xC: 4, yC: 6},
  // "wP6": {view: {}, pngPos: "65px -3px", dragging: false, dead: false, clicked: false, xC: 5, yC: 6},
  // "wP7": {view: {}, pngPos: "65px -3px", dragging: false, dead: false, clicked: false, xC: 6, yC: 6},
  // "wP8": {view: {}, pngPos: "65px -3px", dragging: false, dead: false, clicked: false, xC: 7, yC: 6},
  // "bR1": {view: {}, pngPos: "130px 63px", dragging: false, dead: false, clicked: false, xC: 0, yC: 0},
  // "bR2": {view: {}, pngPos: "130px 63px", dragging: false, dead: false, clicked: false, xC: 7, yC: 0},
  // "bN1": {view: {}, pngPos: "197px 63px", dragging: false, dead: false, clicked: false, xC: 1, yC: 0},
  // "bN2": {view: {}, pngPos: "197px 63px", dragging: false, dead: false, clicked: false, xC: 6, yC: 0},
  // "bB1": {view: {}, pngPos: "-136px 63px", dragging: false, dead: false, clicked: false, xC: 2, yC: 0},
  // "bB2": {view: {}, pngPos: "-136px 63px", dragging: false, dead: false, clicked: false, xC: 5, yC: 0},
  "bK": {view: {}, pngPos: "-4px 63px", dragging: false, dead: false, clicked: false, xC: 4, yC: 0},
  // "bQ": {view: {}, pngPos: "-70px 63px", dragging: false, dead: false, clicked: false, xC: 3, yC: 0},
  // "bP1": {view: {}, pngPos: "65px 63px", dragging: false, dead: false, clicked: false, xC: 0, yC: 1},
  // "bP2": {view: {}, pngPos: "65px 63px", dragging: false, dead: false, clicked: false, xC: 1, yC: 1},
  // "bP3": {view: {}, pngPos: "65px 63px", dragging: false, dead: false, clicked: false, xC: 2, yC: 1},
  // "bP4": {view: {}, pngPos: "65px 63px", dragging: false, dead: false, clicked: false, xC: 3, yC: 1},
  // "bP5": {view: {}, pngPos: "65px 63px", dragging: false, dead: false, clicked: false, xC: 4, yC: 1},
  // "bP6": {view: {}, pngPos: "65px 63px", dragging: false, dead: false, clicked: false, xC: 5, yC: 1},
  // "bP7": {view: {}, pngPos: "65px 63px", dragging: false, dead: false, clicked: false, xC: 6, yC: 1},
  // "bP8": {view: {}, pngPos: "65px 63px", dragging: false, dead: false, clicked: false, xC: 7, yC: 1},
};
// export const PIECE_OBJECTS = {
//   "wR1": {view: {}, pngPos: "130px -3px", dragging: false, dead: false, clicked: false, xC: 0, yC: 7},
//   "wR2": {view: {}, pngPos: "130px -3px", dragging: false, dead: false, clicked: false, xC: 7, yC: 7},
//   "wN1": {view: {}, pngPos: "197px -3px", dragging: false, dead: false, clicked: false, xC: 1, yC: 7},
//   "wN2": {view: {}, pngPos: "197px -3px", dragging: false, dead: false, clicked: false, xC: 6, yC: 7},
//   "wB1": {view: {}, pngPos: "-136px -3px", dragging: false, dead: false, clicked: false, xC: 2, yC: 7},
//   "wB2": {view: {}, pngPos: "-136px -3px", dragging: false, dead: false, clicked: false, xC: 5, yC: 7},
//   "wK": {view: {}, pngPos: "-4px -3px", dragging: false, dead: false, clicked: false, xC: 4, yC: 7},
//   "wQ": {view: {}, pngPos: "-70px -3px", dragging: false, dead: false, clicked: false, xC: 3, yC: 7},
//   "wP1": {view: {}, pngPos: "65px -3px", dragging: false, dead: false, clicked: false, xC: 0, yC: 6},
//   "wP2": {view: {}, pngPos: "65px -3px", dragging: false, dead: false, clicked: false, xC: 1, yC: 6},
//   "wP3": {view: {}, pngPos: "65px -3px", dragging: false, dead: false, clicked: false, xC: 2, yC: 6},
//   "wP4": {view: {}, pngPos: "65px -3px", dragging: false, dead: false, clicked: false, xC: 3, yC: 6},
//   "wP5": {view: {}, pngPos: "65px -3px", dragging: false, dead: false, clicked: false, xC: 4, yC: 6},
//   "wP6": {view: {}, pngPos: "65px -3px", dragging: false, dead: false, clicked: false, xC: 5, yC: 6},
//   "wP7": {view: {}, pngPos: "65px -3px", dragging: false, dead: false, clicked: false, xC: 6, yC: 6},
//   "wP8": {view: {}, pngPos: "65px -3px", dragging: false, dead: false, clicked: false, xC: 7, yC: 6},
//   "bR1": {view: {}, pngPos: "130px 63px", dragging: false, dead: false, clicked: false, xC: 0, yC: 0},
//   "bR2": {view: {}, pngPos: "130px 63px", dragging: false, dead: false, clicked: false, xC: 7, yC: 0},
//   "bN1": {view: {}, pngPos: "197px 63px", dragging: false, dead: false, clicked: false, xC: 1, yC: 0},
//   "bN2": {view: {}, pngPos: "197px 63px", dragging: false, dead: false, clicked: false, xC: 6, yC: 0},
//   "bB1": {view: {}, pngPos: "-136px 63px", dragging: false, dead: false, clicked: false, xC: 2, yC: 0},
//   "bB2": {view: {}, pngPos: "-136px 63px", dragging: false, dead: false, clicked: false, xC: 5, yC: 0},
//   "bK": {view: {}, pngPos: "-4px 63px", dragging: false, dead: false, clicked: false, xC: 4, yC: 0},
//   "bQ": {view: {}, pngPos: "-70px 63px", dragging: false, dead: false, clicked: false, xC: 3, yC: 0},
//   "bP1": {view: {}, pngPos: "65px 63px", dragging: false, dead: false, clicked: false, xC: 0, yC: 1},
//   "bP2": {view: {}, pngPos: "65px 63px", dragging: false, dead: false, clicked: false, xC: 1, yC: 1},
//   "bP3": {view: {}, pngPos: "65px 63px", dragging: false, dead: false, clicked: false, xC: 2, yC: 1},
//   "bP4": {view: {}, pngPos: "65px 63px", dragging: false, dead: false, clicked: false, xC: 3, yC: 1},
//   "bP5": {view: {}, pngPos: "65px 63px", dragging: false, dead: false, clicked: false, xC: 4, yC: 1},
//   "bP6": {view: {}, pngPos: "65px 63px", dragging: false, dead: false, clicked: false, xC: 5, yC: 1},
//   "bP7": {view: {}, pngPos: "65px 63px", dragging: false, dead: false, clicked: false, xC: 6, yC: 1},
//   "bP8": {view: {}, pngPos: "65px 63px", dragging: false, dead: false, clicked: false, xC: 7, yC: 1},
// };
